const ENV = {
  RECIPE_SEARCH_APP_ID: process.env.REACT_APP_RECIPE_SEARCH_APP_ID,
  RECIPE_SEARCH_APP_KEY: process.env.REACT_APP_RECIPE_SEARCH_APP_KEY,
  FOOD_APP_ID: process.env.REACT_APP_FOOD_APP_ID,
  FOOD_APP_KEY: process.env.REACT_APP_FOOD_APP_KEY,
  BASE_RECIPE_URL: process.env.REACT_APP_BASE_RECIPE_URL,
  BASE_FOOD_URL: process.env.REACT_APP_BASE_FOOD_URL,
};

export default ENV;
